### ISSUE TITLE
Renderer cannot capture multiple variables

### ISSUE THREAD

**Issue by braasch-cai** [idling-mind/pptx_renderer#11]
There is a bug on line 95 in `pptx_renderer.py`. It will fail with multiple variables in one textbox. You need to add a non-greedy operator `?` such that the line becomes `matches = re.finditer(r"{{{(.*?)}}}", shape.text)`. Then it works.

**Comment by idling-mind** [comment]
You're right; that's a bug. Will rollout a fix soon! Thanks for reporting it.

**Comment by braasch-cai** [comment]
Great thanks :)! Sorry, was to lazy to open a PR ...

**Comment by idling-mind** [comment]
No problem! You gave the solution anyway!
